name: Build Pull Request

on:
  pull_request: {}

jobs:
    build:
      permissions: write-all
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: ⎔ Setup node
          uses: actions/setup-node@v3
          with:
            node-version-file: '.nvmrc'
            cache: 'yarn'
            cache-dependency-path: '**/bun.lockb'

        - uses: oven-sh/setup-bun@v1
          with:
            bun-version: canary
  
        - name: Restore/create node_modules cache
          uses: actions/cache@v3
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
  
        - name: Install dependencies
          run: bun install
          env:
            HUSKY: 0
  
        - name: Build sources
          run: bun run build
  
        - name: Build showcases
          run: bun run build-storybook