name: Build Pull Request

on:
  pull_request: {}

jobs:
    build:
      permissions: write-all
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
  
        - uses: actions/setup-node@v1
          with:
            node-version: '14.x'
            registry-url: 'https://registry.npmjs.org'
  
        - name: Restore/create node_modules cache
          uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
  
        - name: Install dependencies
          run: yarn install --frozen-lockfile
          env:
            HUSKY: 0
  
        - name: Build sources
          run: yarn build
  
        - name: Build showcases
          run: yarn build-storybook