name: Deploy Storybook

on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ssh-strict: false

      - name: Set git configuration
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Restore/create node_modules cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install
        env:
          HUSKY: 0

      - name: Build
        run: yarn build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/ui/docs
          commit-message: 'chore: deploy storybook'
          single-commit: true
          force: true
          clean: true
          clean-exclude: |
            .nojekyll
